stateDiagram-v2
    direction LR
    state "x1 = 2" as x1
    state "x2 = 4" as x2
    state "v1 = x1x2 = 8" as v1
    state "v2 = ln(x1) = 0.7" as v2
    state "v3 = v1 + x2 = 12" as v3
    state "v4 = v3 - v2 = 11.3" as v4
    state "y = 11.3" as y
    x1 --> v2
    x1 --> v1
    x2 --> v1
    x2 --> v3
    v1 --> v3
    v2 --> v4
    v3 --> v4
    v4 --> y
